### ISSUE TITLE
Get splits in seconds

### ISSUE THREAD

**Issue by jaka87** [cwarwicker/Waddle#5]
Hi there. Im looking around for decent GPS parser. 

Im very new to GPS data so im not sure i get everything. I would like to parse gpx files and get data relevand for windsurfing. This would be speed at  2sec max peak, average of five 10s runs, nautical mile, 1 hour.

So if I understand correctly with getSplits i would be able to split data for example in miles return it in array and get speed for this for each new point right ?

Any idea how to split data by seconds and then get the speed from that points ?

Regards, Jaka

**Comment by cwarwicker** [comment]
Hi, it's been a while since I looked at this project, to be honest I can't really remember what I was doing with the splits, it looks like all you can do with them is basically get a count of miles or km, referencing the key of trackpoints. I probably meant to do more with them, but never got around to it.
